package pdfcpu

import (
	"bytes"
	"fmt"
	"strings"
	"testing"

	"github.com/model-harness/pdftools/objects"
)

// markedPDF builds a one-page PDF whose content stream marks content with a property
// list the page's /Resources does not declare.
//
// Written out byte by byte rather than generated by a typesetter, because no producer
// this repo can drive emits the shape: it is what a real one got wrong. ISO/TS 32002's
// cover page declares /MC0 in a BDC operand and carries no /Properties subdictionary,
// which is invalid — §14.6.2 requires the property list to be resolvable — and it is also
// the file a reader has to read anyway. Keeping the bytes here is what lets a clone with
// no corpus run this: the guard in cmd/pdfspec covers the same class over the real
// documents and skips when they are absent, which is the same as not covering it.
func markedPDF(withProperties bool) []byte {
	res := "<</Font<</F1 5 0 R>>>>"
	if withProperties {
		res = "<</Font<</F1 5 0 R>>/Properties<</MC0 <</Type/OCG/Name(layer)>>>>>>"
	}
	content := "/OC /MC0 BDC BT /F1 12 Tf 72 700 Td (Cover) Tj ET EMC\n"
	objs := []string{
		"<</Type/Catalog/Pages 2 0 R>>",
		"<</Type/Pages/Kids[3 0 R]/Count 1>>",
		"<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources" + res + "/Contents 4 0 R>>",
		fmt.Sprintf("<</Length %d>>\nstream\n%sendstream", len(content), content),
		"<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>",
	}

	var b bytes.Buffer
	b.WriteString("%PDF-1.7\n")
	offsets := make([]int, len(objs))
	for i, o := range objs {
		offsets[i] = b.Len()
		fmt.Fprintf(&b, "%d 0 obj\n%s\nendobj\n", i+1, o)
	}
	start := b.Len()
	fmt.Fprintf(&b, "xref\n0 %d\n0000000000 65535 f \n", len(objs)+1)
	for _, off := range offsets {
		fmt.Fprintf(&b, "%010d 00000 n \n", off)
	}
	fmt.Fprintf(&b, "trailer\n<</Size %d/Root 1 0 R>>\nstartxref\n%d\n%%%%EOF\n", len(objs)+1, start)
	return b.Bytes()
}

// TestPageWithAnUndeclaredPropertyListLoads pins the reason Page does not ask pdfcpu to
// consolidate a page's resources.
//
// Consolidation parses the content stream, computes which resources are used, prunes the
// dictionary to those, and fails the whole page when a used name has no subdictionary. That
// turned one real page into no page at all: ISO/TS 32002's cover was absent from every
// conversion this repo produced, in every mode, and the command exited 0. Reading a page and
// validating its resources are different jobs, and this package's contract is the first one.
//
// The control case matters as much as the failing one. If the declared form did not load
// either, the test would be pinning something other than the missing subdictionary.
func TestPageWithAnUndeclaredPropertyListLoads(t *testing.T) {
	for _, c := range []struct {
		name  string
		props bool
	}{
		{"no /Properties for the /MC0 the content marks with", false},
		{"/Properties declared, the valid form of the same page", true},
	} {
		t.Run(c.name, func(t *testing.T) {
			s, err := New(bytes.NewReader(markedPDF(c.props)))
			if err != nil {
				t.Fatalf("New: %v", err)
			}
			defer func() { _ = s.Close() }()

			if got := s.PageCount(); got != 1 {
				t.Fatalf("PageCount = %d, want 1", got)
			}
			page, err := s.Page(1)
			if err != nil {
				t.Fatalf("Page(1): %v", err)
			}
			// The resource dictionary has to survive, not merely the page: a page whose
			// fonts are gone reads as blank, which is the same loss by another route.
			r, ok := objects.GetDict(s, page, "Resources")
			if !ok {
				t.Fatal("no /Resources on the page")
			}
			if f, ok := objects.GetDict(s, r, "Font"); !ok || f["F1"] == nil {
				t.Errorf("/Font/F1 missing from resources: %v", r)
			}
			content, err := s.PageContent(1)
			if err != nil {
				t.Fatalf("PageContent(1): %v", err)
			}
			if !strings.Contains(string(content), "(Cover) Tj") {
				t.Errorf("content stream = %q, want the show operator", content)
			}
		})
	}
}

// inheritedPDF builds a three-level page tree that splits /Resources across two levels: the
// root declares F1, an intermediate node declares F2, and the leaf page declares none.
//
// The shape exists to pin which of two readings of §7.7.3.4 this package takes. The clause
// says an inheritable value is taken as-is, "without merging, even for composite data types
// such as arrays and dictionaries", and that the search stops at the first /Resources found.
// So the answer is F2 alone — the intermediate node's dictionary in its entirety — and not
// the union. Asking pdfcpu to consolidate resources produced the union, which is the reading
// the clause forbids and which objects.Store.Page's own comment cites the clause against.
//
// No page in the corpus can tell the two apart: all 1,251 declare their own /Resources, which
// is what §7.7.3.4's note tells writers to do. That is exactly why this is a fixture.
func inheritedPDF() []byte {
	objs := []string{
		"<</Type/Catalog/Pages 2 0 R>>",
		"<</Type/Pages/Kids[3 0 R]/Count 1/Resources<</Font<</F1 6 0 R>>/XObject<</Im1 6 0 R>>>>>>",
		"<</Type/Pages/Parent 2 0 R/Kids[4 0 R]/Count 1/Resources<</Font<</F2 6 0 R>>>>>>",
		"<</Type/Page/Parent 3 0 R/MediaBox[0 0 612 792]/Contents 5 0 R>>",
		// The content draws from *both* levels' fonts, which is what makes the two readings
		// observable: a merge resolves F1 and the clause's nearest-ancestor rule does not.
		// With only F2 in the stream, consolidation prunes the merged dictionary back to F2
		// and the two readings agree by coincidence — which is how the first version of this
		// fixture passed under both.
		"<</Length 56>>\nstream\nBT /F1 12 Tf 72 700 Td (Root) Tj /F2 12 Tf (Near) Tj ET\nendstream",
		"<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>",
	}
	var b bytes.Buffer
	b.WriteString("%PDF-1.7\n")
	offsets := make([]int, len(objs))
	for i, o := range objs {
		offsets[i] = b.Len()
		fmt.Fprintf(&b, "%d 0 obj\n%s\nendobj\n", i+1, o)
	}
	start := b.Len()
	fmt.Fprintf(&b, "xref\n0 %d\n0000000000 65535 f \n", len(objs)+1)
	for _, off := range offsets {
		fmt.Fprintf(&b, "%010d 00000 n \n", off)
	}
	fmt.Fprintf(&b, "trailer\n<</Size %d/Root 1 0 R>>\nstartxref\n%d\n%%%%EOF\n", len(objs)+1, start)
	return b.Bytes()
}

// TestInheritedResourcesStopAtTheNearestAncestor pins §7.7.3.4's "without merging".
func TestInheritedResourcesStopAtTheNearestAncestor(t *testing.T) {
	s, err := New(bytes.NewReader(inheritedPDF()))
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	defer func() { _ = s.Close() }()

	page, err := s.Page(1)
	if err != nil {
		t.Fatalf("Page(1): %v", err)
	}
	r, ok := objects.GetDict(s, page, "Resources")
	if !ok {
		t.Fatal("no /Resources reached the page: an inheritable value was not inherited at all")
	}
	f, ok := objects.GetDict(s, r, "Font")
	if !ok {
		t.Fatalf("no /Font in the inherited resources: %v", r)
	}
	if f["F2"] == nil {
		t.Errorf("/Font/F2 missing: the nearest ancestor's dictionary is the one that applies, got %v", f)
	}
	// F1 is in the root's dictionary and the content stream names it, so a reader that merges
	// resolves it. §7.7.3.4 stops the search at the first /Resources found and applies that
	// value in its entirety, so F1 is not in scope for this page and the glyphs it draws are
	// not recoverable — a statement about the file, not about this package. Leniency here
	// would be a different contract from the one objects.Store.Page documents.
	if f["F1"] != nil {
		t.Errorf("/Font/F1 present: the root's dictionary was merged in, which §7.7.3.4 forbids — got %v", f)
	}
	if _, merged := objects.GetDict(s, r, "XObject"); merged {
		t.Error("/XObject present: only the root declares one, so it was merged rather than replaced")
	}
}
