// Package content reads PDF content streams: the token stream, and the graphics
// and text state machine that turns operators into positioned glyphs.
//
// A content stream is a sequence of operands followed by an operator, in
// postfix order (ISO 32000-2 §7.8.2). The syntax is the same as the object
// syntax in §7.3 with two differences: there are no indirect references, and
// bare keywords are operators rather than errors.
//
// This package is deliberately tolerant. Content streams are the part of a PDF
// most often malformed, because they are generated by drawing code rather than
// written by a serializer, and a stream that stops tokenizing at the first
// oddity loses the rest of the page.
package content

import (
	"strconv"

	"github.com/model-harness/pdftools/objects"
)

// Character classes per ISO 32000-2 §7.2.3. These are lookup tables rather than
// switch statements because they are consulted once per byte of every content
// stream in the document, which is the hottest loop in extraction.
var (
	isSpace   [256]bool
	isDelim   [256]bool
	isRegular [256]bool
)

func init() {
	// NUL, TAB, LF, FF, CR, SP.
	for _, c := range []byte{0x00, 0x09, 0x0A, 0x0C, 0x0D, 0x20} {
		isSpace[c] = true
	}
	for _, c := range []byte("()<>[]{}/%") {
		isDelim[c] = true
	}
	for i := range isRegular {
		isRegular[i] = !isSpace[i] && !isDelim[i]
	}
}

// Kind distinguishes the token classes a content stream can hold.
type Kind uint8

const (
	// KindEOF marks the end of the stream.
	KindEOF Kind = iota
	// KindObject is a complete direct object: number, string, name, boolean, null.
	KindObject
	// KindArrayOpen and the three that follow are structural punctuation. They are
	// tokens rather than assembled objects because the lexer does not recurse;
	// assembly is the scanner's job, which keeps nesting depth bounded by the
	// scanner's explicit limit instead of by the call stack.
	KindArrayOpen
	KindArrayClose
	KindDictOpen
	KindDictClose
	// KindOperator is a bare keyword: an operator such as Tj, or a stray token.
	KindOperator
)

// Token is one lexical unit. Val is set when Kind is KindObject, Op when Kind is
// KindOperator.
type Token struct {
	Kind Kind
	Val  objects.Object
	Op   string
	Pos  int
}

// Lexer tokenizes a content stream. It holds no state beyond a position, so a
// caller may record Pos and resume.
type Lexer struct {
	data []byte
	pos  int
}

// NewLexer returns a Lexer over data. The slice is not copied and must not be
// modified while lexing.
func NewLexer(data []byte) *Lexer { return &Lexer{data: data} }

// Pos returns the current byte offset.
func (l *Lexer) Pos() int { return l.pos }

// Next returns the next token, or a KindEOF token at the end of the stream.
func (l *Lexer) Next() Token {
	for {
		l.skipSpace()
		if l.pos >= len(l.data) {
			return Token{Kind: KindEOF, Pos: l.pos}
		}
		start := l.pos
		c := l.data[l.pos]

		switch c {
		case '[':
			l.pos++
			return Token{Kind: KindArrayOpen, Pos: start}
		case ']':
			l.pos++
			return Token{Kind: KindArrayClose, Pos: start}
		case '(':
			return Token{Kind: KindObject, Val: l.literalString(), Pos: start}
		case '/':
			return Token{Kind: KindObject, Val: l.name(), Pos: start}
		case '<':
			if l.pos+1 < len(l.data) && l.data[l.pos+1] == '<' {
				l.pos += 2
				return Token{Kind: KindDictOpen, Pos: start}
			}
			return Token{Kind: KindObject, Val: l.hexString(), Pos: start}
		case '>':
			if l.pos+1 < len(l.data) && l.data[l.pos+1] == '>' {
				l.pos += 2
				return Token{Kind: KindDictClose, Pos: start}
			}
			// A lone '>' is malformed. Skipping it and continuing keeps the rest
			// of the page; the loop rather than recursion means a stream of them
			// cannot exhaust the stack.
			l.pos++
			continue
		case '{', '}':
			// PostScript calculator function braces. Not legal in a content
			// stream, but harmless to skip if a producer emits them.
			l.pos++
			continue
		}

		if c == '+' || c == '-' || c == '.' || (c >= '0' && c <= '9') {
			return Token{Kind: KindObject, Val: l.number(), Pos: start}
		}
		return l.keyword(start)
	}
}

// skipSpace advances past whitespace and comments. A comment runs to the end of
// the line (§7.2.4).
func (l *Lexer) skipSpace() {
	for l.pos < len(l.data) {
		c := l.data[l.pos]
		if isSpace[c] {
			l.pos++
			continue
		}
		if c == '%' {
			for l.pos < len(l.data) && l.data[l.pos] != '\n' && l.data[l.pos] != '\r' {
				l.pos++
			}
			continue
		}
		return
	}
}

// operators interns the operator names of ISO 32000-2 Annex A.
//
// Every operator in every content stream would otherwise allocate a string for
// its name, and a 1,000-page document runs millions of operators. Looking the
// bytes up here returns a string that already exists: Go compiles a map index
// keyed by string(b) without copying b, so a recognized operator costs nothing.
// Unrecognized names still allocate, which is correct — they are rare, and the
// alternative is an unbounded cache keyed by attacker-controlled bytes.
var operators = func() map[string]string {
	names := []string{
		// Graphics state.
		"q", "Q", "cm", "w", "J", "j", "M", "d", "ri", "i", "gs",
		// Path construction and painting.
		"m", "l", "c", "v", "y", "h", "re",
		"S", "s", "f", "F", "f*", "B", "B*", "b", "b*", "n", "W", "W*",
		// Text.
		"BT", "ET", "Tc", "Tw", "Tz", "TL", "Tf", "Tr", "Ts",
		"Td", "TD", "Tm", "T*", "Tj", "TJ", "'", `"`,
		// Type 3 glyph metrics.
		"d0", "d1",
		// Colour.
		"CS", "cs", "SC", "SCN", "sc", "scn", "G", "g", "RG", "rg", "K", "k",
		// XObjects, images, and shading.
		"BI", "ID", "EI", "Do", "sh",
		// Marked content and compatibility.
		"MP", "DP", "BMC", "BDC", "EMC", "BX", "EX",
	}
	m := make(map[string]string, len(names))
	for _, n := range names {
		m[n] = n
	}
	return m
}()

// keyword reads a bare token: an operator, or one of the three keyword objects.
func (l *Lexer) keyword(start int) Token {
	for l.pos < len(l.data) && isRegular[l.data[l.pos]] {
		l.pos++
	}
	if l.pos == start {
		// Not regular and not handled above: an unexpected delimiter. Consume it
		// so the caller cannot loop.
		l.pos++
		return Token{Kind: KindOperator, Op: string(l.data[start:l.pos]), Pos: start}
	}
	word := l.data[start:l.pos]
	switch string(word) {
	case "true":
		return Token{Kind: KindObject, Val: objects.Bool(true), Pos: start}
	case "false":
		return Token{Kind: KindObject, Val: objects.Bool(false), Pos: start}
	case "null":
		return Token{Kind: KindObject, Val: objects.Null{}, Pos: start}
	}
	if op, ok := operators[string(word)]; ok {
		return Token{Kind: KindOperator, Op: op, Pos: start}
	}
	return Token{Kind: KindOperator, Op: string(word), Pos: start}
}

// number reads a numeric object, returning Int when the token has no fractional
// part so that callers needing an integer (a font size, an MCID) get one.
func (l *Lexer) number() objects.Object {
	start := l.pos
	real := false
	for l.pos < len(l.data) {
		c := l.data[l.pos]
		if c >= '0' && c <= '9' {
			l.pos++
			continue
		}
		// Signs are consumed inside the token, not just at its head: producers
		// emit "--5" and "1-2", and stopping early would leave a stray token that
		// shifts every following operand by one.
		if c == '.' || c == '+' || c == '-' {
			if c == '.' {
				real = true
			}
			l.pos++
			continue
		}
		break
	}
	raw := l.data[start:l.pos]

	if !real {
		if n, err := strconv.ParseInt(string(raw), 10, 64); err == nil {
			return objects.Int(n)
		}
	}
	if f, err := strconv.ParseFloat(string(raw), 64); err == nil {
		if !real {
			return objects.Int(int64(f))
		}
		return objects.Real(f)
	}
	return salvageNumber(raw, real)
}

// salvageNumber parses a number that strconv rejected, by keeping the first sign
// and the first decimal point and discarding the rest. "--5" becomes -5 and
// "1-2" becomes 1, which is what viewers do, and is better than dropping the
// operand and misaligning everything after it.
func salvageNumber(raw []byte, real bool) objects.Object {
	buf := make([]byte, 0, len(raw))
	seenDot, seenDigit := false, false
	for i, c := range raw {
		switch {
		case c == '-' || c == '+':
			// A sign is only meaningful before any digit.
			if i == 0 && c == '-' {
				buf = append(buf, c)
			} else if seenDigit {
				// A sign after digits terminates the number: "1-2" is 1.
				goto done
			}
		case c == '.':
			if seenDot {
				goto done
			}
			seenDot = true
			buf = append(buf, c)
		default:
			seenDigit = true
			buf = append(buf, c)
		}
	}
done:
	if !seenDigit {
		return objects.Int(0)
	}
	if f, err := strconv.ParseFloat(string(buf), 64); err == nil {
		if real || seenDot {
			return objects.Real(f)
		}
		return objects.Int(int64(f))
	}
	return objects.Int(0)
}

// name reads a name object, resolving #xx escapes (§7.3.5).
func (l *Lexer) name() objects.Name {
	l.pos++ // the '/'
	start := l.pos
	hasEscape := false
	for l.pos < len(l.data) && isRegular[l.data[l.pos]] {
		if l.data[l.pos] == '#' {
			hasEscape = true
		}
		l.pos++
	}
	raw := l.data[start:l.pos]
	if !hasEscape {
		return objects.Name(raw)
	}
	out := make([]byte, 0, len(raw))
	for i := 0; i < len(raw); i++ {
		if raw[i] == '#' && i+2 < len(raw) {
			hi, ok1 := hexVal(raw[i+1])
			lo, ok2 := hexVal(raw[i+2])
			if ok1 && ok2 {
				out = append(out, hi<<4|lo)
				i += 2
				continue
			}
		}
		out = append(out, raw[i])
	}
	return objects.Name(out)
}

// literalString reads a (...) string, resolving escapes per §7.3.4.2.
func (l *Lexer) literalString() objects.String {
	l.pos++ // the '('
	depth := 1
	out := make([]byte, 0, 32)
	for l.pos < len(l.data) {
		c := l.data[l.pos]
		l.pos++
		switch c {
		case '(':
			depth++
			out = append(out, c)
		case ')':
			depth--
			if depth == 0 {
				return out
			}
			out = append(out, c)
		case '\\':
			if l.pos >= len(l.data) {
				return out
			}
			e := l.data[l.pos]
			l.pos++
			switch e {
			case 'n':
				out = append(out, '\n')
			case 'r':
				out = append(out, '\r')
			case 't':
				out = append(out, '\t')
			case 'b':
				out = append(out, '\b')
			case 'f':
				out = append(out, '\f')
			case '(', ')', '\\':
				out = append(out, e)
			case '\r':
				// Backslash before an end-of-line is a line continuation: the
				// break is not part of the string. CRLF counts as one break.
				if l.pos < len(l.data) && l.data[l.pos] == '\n' {
					l.pos++
				}
			case '\n':
				// Line continuation.
			default:
				if e >= '0' && e <= '7' {
					// Octal escape, one to three digits. Three digits reach 511,
					// so the conversion to byte can truncate — and must:
					// §7.3.4.2 Table 3 specifies that a value above 255 has its
					// high-order overflow ignored, making \777 equal 0xFF.
					v := int(e - '0')
					for n := 0; n < 2 && l.pos < len(l.data); n++ {
						d := l.data[l.pos]
						if d < '0' || d > '7' {
							break
						}
						v = v*8 + int(d-'0')
						l.pos++
					}
					out = append(out, byte(v)) // #nosec G115 -- truncation is the specified behavior
				} else {
					// An unknown escape drops the backslash and keeps the byte.
					out = append(out, e)
				}
			}
		case '\r':
			// A raw end-of-line inside a string is stored as a single LF.
			if l.pos < len(l.data) && l.data[l.pos] == '\n' {
				l.pos++
			}
			out = append(out, '\n')
		default:
			out = append(out, c)
		}
	}
	// Unterminated string: return what was read rather than nothing.
	return out
}

// hexString reads a <...> string. An odd number of digits is padded with a
// trailing zero per §7.3.4.3.
func (l *Lexer) hexString() objects.String {
	l.pos++ // the '<'
	out := make([]byte, 0, 16)
	var cur byte
	half := false
	for l.pos < len(l.data) {
		c := l.data[l.pos]
		l.pos++
		if c == '>' {
			break
		}
		v, ok := hexVal(c)
		if !ok {
			// Whitespace is legal between digits; anything else is malformed and
			// is skipped rather than aborting the string.
			continue
		}
		if half {
			out = append(out, cur<<4|v)
			half = false
		} else {
			cur = v
			half = true
		}
	}
	if half {
		out = append(out, cur<<4)
	}
	return out
}

func hexVal(c byte) (byte, bool) {
	switch {
	case c >= '0' && c <= '9':
		return c - '0', true
	case c >= 'a' && c <= 'f':
		return c - 'a' + 10, true
	case c >= 'A' && c <= 'F':
		return c - 'A' + 10, true
	}
	return 0, false
}
